Loja Quadrinhos/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Loja_Quadrinhos.Models;
using Loja_Quadrinhos.Repositories;
using Loja_Quadrinhos.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Loja_Quadrinhos.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProdutoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Listar()
        {
            var produtos = _unitOfWork.ProdutoRepository.Get().OrderBy(produto => produto.QuantidadeVendidos);
            if (produtos != null)
            {
                return View(produtos);
            }
            return View("Error");
        }

        public IActionResult ListarProdutoPorCategoria(int categoriaId)
        {
            var categoria = _unitOfWork.CategoriaRepository.GetById(categoriaId);
            var produtos = _unitOfWork.ProdutoRepository.GetByCategoria(categoria);
            if (produtos != null)
            {
                return View(produtos);
            }
            return View("Error");
        }

        public IActionResult Detalhes(int produtoId)
        {
            Produto produto = _unitOfWork.ProdutoRepository.GetById(produtoId);
            return View(produto);
        }
    }
}

Loja Quadrinhos/Views/Shared/Components/CategoriaMenu/Default.cshtml
@model IEnumerable<Categoria>

<li class="dropdown show">
    <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" id="dropdownMenuButton" style="margin-right:20px">Produtos   </a>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        @foreach (Categoria categoria in Model)
        {
            <li>
                <a class="dropdown-item" asp-controller="Produto" asp-action="ListarProdutoPorCategoria"
                   asp-route-categoriaId="@categoria.CategoriaId">@categoria.CategoriaNome</a>
            </li>
        }
        <li class="dropdown-divider"></li>
        <li>
            <a class="dropdown-item" asp-controller="Produto" asp-action="Listar" asp-route-categoria="">Todos os Quadrinhos</a>
        </li>
    </ul>
</li>