Loja Quadrinhos/Models/Produto.cs
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Loja_Quadrinhos.Models
{
    public class Produto
    {
        public int ProdutoId { get; set; }
        
        [Required]
        [Display(Name = "Título do quadrinho")]
        [StringLength(80, MinimumLength = 4)]
        public string Titulo { get; set; }

        [Required]
        [Display(Name = "Autor da obra")]
        [StringLength(60, MinimumLength = 4)]
        public string Autor { get; set; }

        [Required]
        public int CategoriaId { get; set; }
        public virtual Categoria Categoria { get; set; }

        [Required]
        [Display(Name = "Descrição detalhada do Quadrinho")]
        [MinLength(20)]
        [MaxLength(200)]
        public string Descricao { get; set; }

        [Required]
        [Display(Name = "Caminho Imagem")]
        [StringLength(200)]
        public string ImagemUrl { get; set; }

        [NotMapped]
        [DisplayName("Upload file")]
        public IFormFile ImageFile { get; set; }

        [Required]
        public decimal Preco { get; set; }


        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public int QuantidadeVendidos { get; set; }


        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid integer Number")]
        public int QuantidadeEmEstoque { get; set; }

        public Produto()
        {
            QuantidadeEmEstoque = 0;
            QuantidadeVendidos = 0;
        }

        public Produto(string titulo, string autor, int categoriaId, Categoria categoria, string descricao, string imagemUrl, decimal preco, int quantidadeVendidos, int quantidadeEmEstoque)
        {
            Titulo = titulo;
            Autor = autor;
            CategoriaId = categoriaId;
            Categoria = categoria;
            Descricao = descricao;
            ImagemUrl = imagemUrl;
            Preco = preco;
            QuantidadeVendidos = quantidadeVendidos;
            QuantidadeEmEstoque = quantidadeEmEstoque;
        }

        public Produto(int produtoId, string titulo, string autor, int categoriaId, Categoria categoria, string descricao, string imagemUrl, decimal preco, int quantidadeVendidos, int quantidadeEmEstoque)
        {
            ProdutoId = produtoId;
            Titulo = titulo;
            Autor = autor;
            CategoriaId = categoriaId;
            Categoria = categoria;
            Descricao = descricao;
            ImagemUrl = imagemUrl;
            Preco = preco;
            QuantidadeVendidos = quantidadeVendidos;
            QuantidadeEmEstoque = quantidadeEmEstoque;
        }

        public void AtualizarPreco(decimal novoPreco)
        {
            this.Preco = novoPreco;
        }

        public string ObterImg()
        {
            return @"./www";
        }
    }
}

Loja Quadrinhos/Controllers/CarrinhoCompraController.cs
using Loja_Quadrinhos.Models;
using Loja_Quadrinhos.Repositories.Interfaces;
using Loja_Quadrinhos.Services;
using Loja_Quadrinhos.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Loja_Quadrinhos.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private CarrinhoCompraService _carrrinhoCompraService;
        private UserManager<Usuario> _userManager;
        private IUnitOfWork _unitOfWork;

        public CarrinhoCompraController(CarrinhoCompraService carrinhoCompraService, UserManager<Usuario> userManager, IUnitOfWork unitOfWork)
        {
            _carrrinhoCompraService = carrinhoCompraService;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }

        public IActionResult AdicionarAoCarrinho(int produtoId)
        {
            _carrrinhoCompraService.AdicionarItemNoCarrinhoCompra(produtoId, 1);
            return RedirectToAction("ListarItens");
        }

        public IActionResult RemoverDoCarrinho(int produtoId)
        {
            _carrrinhoCompraService.RemoverItemDoCarrinhoCompra(produtoId);
            if (_carrrinhoCompraService.GetCarrinhoCompraQuantidade() == 0)
            {
                return View("ListaItensVazia");
            }
            return RedirectToAction("ListarItens");
        }
        
        public IActionResult ListarItens()
        {

            var carrinhoCompraVM = new CarrinhoCompraVM
            {
                CarrinhoCompraItens = _carrrinhoCompraService.GetItensDoCarrinho(),
                QuantidadeItens = _carrrinhoCompraService.GetCarrinhoCompraQuantidade(),
                Total = _carrrinhoCompraService.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }

        [Authorize(Roles = "Member")]
        public async Task FinalizaPedido()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            _carrrinhoCompraService.FinalizaPedido(user);
        }

    }
}

Loja Quadrinhos/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Loja_Quadrinhos.Models;
using Loja_Quadrinhos.Repositories;
using Loja_Quadrinhos.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Loja_Quadrinhos.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProdutoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Listar()
        {
            var produtos = _unitOfWork.ProdutoRepository.Get().OrderBy(produto => produto.QuantidadeVendidos);
            if (produtos != null)
            {
                return View(produtos);
            }
            return View("Error");
        }

        public IActionResult ListarProdutoPorCategoria(int categoriaId)
        {
            var categoria = _unitOfWork.CategoriaRepository.GetById(categoriaId);
            var produtos = _unitOfWork.ProdutoRepository.GetByCategoria(categoria);
            if (produtos != null)
            {
                return View(produtos);
            }
            return View("Error");
        }

        public IActionResult Detalhes(int produtoId)
        {
            Produto produto = _unitOfWork.ProdutoRepository.GetById(produtoId);
            return View(produto);
        }
    }
}

Loja Quadrinhos/Views/Produto/Detalhes.cshtml
@model Loja_Quadrinhos.Models.Produto

<div class="text-center">
    <h1 class="titulo">@Model.Categoria.CategoriaNome</h1>
</div>

<div class="container" style="margin-top:80px;">
    <div class="row">
        <div class="col-6">
            <div class="img-completa">
                <div class="imagem-completa">
                    <img src="@Model.ImagemUrl" class="img-fluid" />
                </div>
            </div>
        </div>
        <div class="col-6">
            <h1 class="titulo-quadrinho">@Model.Titulo</h1>
            <p class="preco-detalhe">R$ @Model.Preco</p>
            <p class="descricao-detalhe">@Model.Descricao</p>
            <a asp-controller="CarrinhoCompra" asp-action="AdicionarAoCarrinho" asp-route-produtoId="@Model.ProdutoId" class="btn btn-comprar">Adicionar ao Carrinho</a>
        </div>
    </div>
</div>

Loja Quadrinhos/Views/Produto/Listar.cshtml
@model IEnumerable<Loja_Quadrinhos.Models.Produto>

<div class="text-center">
    <h1 class="titulo">Listando produtos</h1>
</div>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3 quadrinho">
                <a asp-action="Detalhes" asp-route-produtoId="@item.ProdutoId">
                    <div class="imagem-miniatura">
                        <img src="@item.ImagemUrl" class="img-fluid" />
                    </div>
                </a>
                <div>
                    <p class="subtitulo">@Html.DisplayFor(modelItem => item.Titulo)</p>
                    <p class="preco">R$ @Html.DisplayFor(modelItem => item.Preco)</p>

                </div>
            </div>
        }
    </div>
</div>

Loja Quadrinhos/Views/Produto/ListarProdutoPorCategoria.cshtml
@model IEnumerable<Loja_Quadrinhos.Models.Produto>

<div class="text-center">
    <h1 class="titulo">Listando produtos</h1>
</div>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3 quadrinho">
                <a asp-action="Detalhes" asp-route-produtoId="@item.ProdutoId" class="imagem-miniatura">
                    <div class="imagem-completa">
                        <img src="@item.ImagemUrl" class="img-fluid" />
                    </div>
                </a>
                <div>
                    <p class="subtitulo">@Html.DisplayFor(modelItem => item.Titulo)</p>
                    <p class="preco">R$ @Html.DisplayFor(modelItem => item.Preco)</p>
                </div>
            </div>
        }
    </div>
</div>