Loja Quadrinhos/Controllers/PedidoController.cs
using Loja_Quadrinhos.Models;
using Loja_Quadrinhos.Repositories;
using Loja_Quadrinhos.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Loja_Quadrinhos.Controllers
{
    [Authorize]
    public class PedidoController : Controller
    {
        private IUnitOfWork UnitOfWork;
        private readonly UserManager<Usuario> _userManager;

        public PedidoController(UnitOfWork unitOfWork, UserManager<Usuario> userManager)
        {
            UnitOfWork = unitOfWork;
            _userManager = userManager;
        }
        public async Task<IActionResult> Listar()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var pedidos = UnitOfWork.PedidoRepository.GetPedidosByUser(user);
            return View(pedidos);
        }

        public IActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = UnitOfWork.PedidoRepository.GetById((int)id);

            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var pedido = UnitOfWork.PedidoRepository.GetById((int)id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, [Bind("PedidoId,UsuarioId,PedidoTotal,DataPedido,PedidoEntregueEm")] Pedido pedido)
        {
            if (id != pedido.PedidoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    UnitOfWork.PedidoRepository.Update(pedido);
                    UnitOfWork.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Listar));
            }
            return View(pedido);
        }

        public IActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = UnitOfWork.PedidoRepository.GetById((int)id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var pedido = UnitOfWork.PedidoRepository.GetById((int)id);
            UnitOfWork.PedidoRepository.Delete(pedido);
            UnitOfWork.Commit();
            return RedirectToAction(nameof(Listar));
        }

        private bool PedidoExists(int id)
        {
            return UnitOfWork.PedidoRepository.GetById(id) != null;
        }
    }
}

Loja Quadrinhos/Views/Shared/ErroListaVazia.cshtml
    @{
        var url = ViewData["Url"];
    }

    <p>Nada a ser exibido! Por favor, Cadastre novos items para serem exibidos!</p>

    <a href="@url/Cadastrar">Cadastre novo item</a>

Loja Quadrinhos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Loja_Quadrinhos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class=" navbar navbar-expand-sm navbar-toggleable-sm barra">
            <div class="container">
                <a class="navbar-brand logo" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/Logo-grande.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 menu">
                        <li class="nav-item menu-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item menu-item">
                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>
                        @if (User.IsInRole("Member"))
                        {
                            <li class="nav-item menu-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Listar">Pedidos</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item menu-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProdutoAdmin" asp-action="Listar">ProdutoAdmin</a>
                            </li>
                            <li class="nav-item menu-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CategoriaAdmin" asp-action="Listar">CategoriaAdmin</a>
                            </li>
                        }

                        <li class="nav-item menu-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="QuemSomos">Quem-Somos</a>
                        </li>
                        <li class="nav-item menu-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contato">Contato</a>
                        </li>


                        @await Component.InvokeAsync("CarrinhoCompraResumo")
                    </ul>
                </div>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </nav>
    </header>
    <div class="conteudo container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Loja_Quadrinhos - Gabriel Bortone
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>